import { describe, expect, it } from "vitest";
import { compile, parse, parseOptions, RevealTeXError } from "../src/index.js";

const config = { components: { MetricCard: { source: "@/MetricCard.vue", props: { value: { type: "number" as const, required: true }, label: { type: "string" as const, required: true } } }, DataChart: { source: "@/DataChart.vue", props: { data: { type: "asset" as const, required: true } } }, FeatureCard: { source: "@/FeatureCard.vue" } } };
describe("parser", () => {
  it("parses nested arguments and preserves locations", () => { const ast=parse("\\fragment{a \\textbf{nested} value}","deck.rtex"); const fragment=ast.children[0]; expect(fragment?.type).toBe("command"); expect(fragment?.location.start).toEqual({line:1,column:1,offset:0}); if(fragment?.type==="command") expect(fragment.requiredArguments[0]?.children[1]?.type).toBe("command"); });
  it("ignores comments but preserves escaped percent",()=>{const ast=parse("hello % gone\n94.7\\%");expect(ast.children.filter(n=>n.type==="text").map(n=>n.value).join("")).toContain("94.7%");expect(JSON.stringify(ast)).not.toContain("gone");});
  it("reports unclosed environments",()=>expect(()=>parse("\\begin{frame}x","x.rtex")).toThrow(RevealTeXError));
  it("parses structured options",()=>expect(parseOptions("value=94.7,label={Validation, Accuracy},active=true")).toEqual({value:94.7,label:"Validation, Accuracy",active:true}));
});
describe("semantic compilation",()=>{
  it("compiles slides, fragments, lists, math and components",()=>{const result=compile(String.raw`\documentclass{reveal}
\title{Demo}\date{August 2026}\transition{slide}\begin{document}\maketitle
\begin{frame}[id=results,transition=zoom]{Results}
\begin{itemize}\item<1-> First\item<2-> Second\end{itemize}
\[x^2\]\MetricCard[value=42,label={Users}]\end{frame}\end{document}`,{file:"deck.rtex",config});expect(result.diagnostics).toEqual([]);expect(result.presentation.slides).toHaveLength(2);expect(result.presentation.slides[0]?.children).toContainEqual(expect.objectContaining({type:"format",style:"date"}));expect(result.presentation.slides[1]).toMatchObject({id:"results",transition:{effect:"zoom"}});expect(JSON.stringify(result.presentation)).toContain('"MetricCard"');const list=result.presentation.slides[1]?.children.find(n=>n.type==="list");expect(list?.type==="list"&&list.items.map(i=>i.index)).toEqual([undefined,1]);});
  it("validates component props",()=>{const result=compile(String.raw`\begin{document}\begin{frame}{X}\MetricCard[value={oops}]\end{frame}\end{document}`,{config});expect(result.diagnostics.some(d=>d.code==="RTX3003")).toBe(true);expect(result.diagnostics.some(d=>d.code==="RTX3001")).toBe(true);});
  it("records typed component assets in the renderer-independent manifest",()=>{const result=compile(String.raw`\begin{document}\begin{frame}{X}\DataChart[data={data/results.json}]\end{frame}\end{document}`,{file:"slides/results.rtex",config});expect(result.diagnostics).toEqual([]);expect(result.presentation.assets).toContainEqual(expect.objectContaining({kind:"data",path:"data/results.json",source:expect.objectContaining({file:"slides/results.rtex"})}));});
  it("turns pause boundaries into staged trailing content",()=>{const result=compile(String.raw`\begin{document}\begin{frame}{Sequence}Always visible.\pause Second step.\pause Third step.\end{frame}\end{document}`);const children=result.presentation.slides[0]?.children??[];expect(children[0]).toMatchObject({type:"paragraph"});expect(children[1]).toMatchObject({type:"fragment",index:1});expect(children[2]).toMatchObject({type:"fragment",index:2});expect(JSON.stringify(children)).not.toContain("__revealtex_pause_boundary__");});
  it("maps plugin commands and environments to validated component IR",()=>{const plugin={name:"domain",components:{PluginMetric:{source:"@/PluginMetric.vue",props:{value:{type:"number" as const,required:true},label:{type:"string" as const}}},PluginPanel:{source:"@/PluginPanel.vue"}},commands:{metric:{component:"PluginMetric",props:({argument}:{argument?:string})=>({value:Number(argument),label:"Score"})}},environments:{panel:{component:"PluginPanel"}}};const result=compile(String.raw`\begin{document}\begin{frame}{Plugin}\metric{94.7}\begin{panel}[tone=quiet]Nested content.\end{panel}\end{frame}\end{document}`,{config:{plugins:[plugin]}});expect(result.diagnostics).toEqual([]);const components=result.presentation.slides[0]?.children.filter(node=>node.type==="component")??[];expect(components[0]).toMatchObject({type:"component",name:"PluginMetric",props:{value:94.7,label:"Score"},children:[]});expect(components[1]).toMatchObject({type:"component",name:"PluginPanel",props:{tone:"quiet"}});expect(JSON.stringify(components[1])).toContain("Nested content.");});
  it("normalizes visual and positioning containers",()=>{const result=compile(String.raw`\begin{document}\begin{frame}{Containers}\card{Card}\callout[info]{Notice}\badge{Beta}\position[x=12,y=20,width=40]{Placed}\end{frame}\end{document}`);expect(result.diagnostics).toEqual([]);expect(result.presentation.slides[0]?.children).toEqual(expect.arrayContaining([expect.objectContaining({type:"container",kind:"card"}),expect.objectContaining({type:"container",kind:"callout",options:{variant:"info"}}),expect.objectContaining({type:"container",kind:"badge"}),expect.objectContaining({type:"container",kind:"position",options:{x:12,y:20,width:40}})]));});
  it("extracts named component slots",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{X}\begin{FeatureCard}\slot{title}{Fast}Body\end{FeatureCard}\end{frame}\end{document}`,{config});const component=r.presentation.slides[0]?.children.find(n=>n.type==="component");expect(component?.type).toBe("component");if(component?.type==="component"){expect(component.slots.title?.[0]?.type).toBe("paragraph");expect(JSON.stringify(component.slots.title)).toContain("Fast");}});
  it("normalizes paragraphs, backgrounds, and optional section dividers",()=>{const r=compile(String.raw`\begin{document}\section{Results}\begin{frame}[background=#10131c]{X}\backgroundgradient{linear-gradient(#111,#222)}First paragraph.

Second paragraph.\end{frame}\end{document}`,{config:{...config,sections:{autoDividerSlides:true}}});expect(r.presentation.slides).toHaveLength(2);expect(r.presentation.slides[0]?.options.sectionDivider).toBe(true);expect(r.presentation.slides[1]?.background).toEqual({color:"#10131c",image:undefined,gradient:"linear-gradient(#111,#222)"});expect(r.presentation.slides[1]?.children.filter(n=>n.type==="paragraph")).toHaveLength(2);});
  it("represents vertical sections without renderer concepts",()=>{const r=compile(String.raw`\begin{document}\begin{section}{Deep Dive}\begin{frame}{Overview}A\end{frame}\begin{subframe}{Detail}B\end{subframe}\end{section}\end{document}`);expect(r.diagnostics).toEqual([]);expect(r.presentation.slides).toHaveLength(2);expect(r.presentation.navigation).toHaveLength(1);expect(r.presentation.navigation[0]).toMatchObject({type:"slide-stack",title:"Deep Dive"});expect(JSON.stringify(r.presentation.navigation)).not.toContain("Vue");});
});
describe("reveal feature coverage",()=>{
  it("maps beamer-style overlay commands and list items onto overlay numbers",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{O}\only<2->{Two}\uncover<3>{Three}\visible<1-2>{Early}\alt<2>{A}{B}\begin{itemize}\item<1-> One\item<3-> Three\end{itemize}\end{frame}\end{document}`);expect(r.diagnostics).toEqual([]);const children=r.presentation.slides[0]?.children??[];const fragments=children.filter(n=>n.type==="fragment");expect(fragments[0]).toMatchObject({only:true,start:2,index:1});expect(fragments[1]).toMatchObject({start:3,end:3,index:2});expect(fragments[2]).toMatchObject({start:1,end:2});expect(fragments[3]).toMatchObject({start:1,end:1});expect(fragments[4]).toMatchObject({start:2,index:1});const list=children.find(n=>n.type==="list");expect(list?.type==="list"&&list.items[0]?.index).toBeUndefined();expect(list?.type==="list"&&list.items[1]).toMatchObject({index:2,start:3});});
  it("supports dollar display math and amsmath environments",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{M}$$a=b$$\begin{align}a&=b\\c&=d\end{align}\begin{equation}e=f\end{equation}\begin{gather}g=h\end{gather}\end{frame}\end{document}`);const math=(r.presentation.slides[0]?.children??[]).filter(n=>n.type==="math");expect(math[0]).toMatchObject({display:true,tex:"a=b"});expect(math[1]).toMatchObject({display:true});expect(math[1]?.tex).toContain("\\begin{align}");expect(math[2]).toMatchObject({display:true,tex:"e=f"});expect(math[3]?.tex).toContain("\\begin{gather}");});
  it("passes reveal frame options through, resolves today, and records backgrounds and themes",()=>{const r=compile(String.raw`\documentclass{reveal}\title{D}\date{\today}\theme{dracula}\begin{document}\begin{frame}[state=intro,background-video=bg.mp4,background-size=cover,background-opacity=0.5,autoslide=4000]{X}Body\end{frame}\end{document}`,{file:"deck.rtex"});const slide=r.presentation.slides[0];expect(r.presentation.configuration.theme).toBe("dracula");expect(r.presentation.metadata.date).not.toContain("\\today");expect(slide?.background).toMatchObject({video:"bg.mp4",size:"cover",opacity:"0.5"});expect(slide?.attributes).toMatchObject({"data-state":"intro","data-autoslide":"4000"});expect(slide?.attributes["data-background-video"]).toBeUndefined();});
  it("compiles reveal layout utility containers",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{U}\fittext{Big}\hstack{A}\vstack{B}\stretch{C}\frame{D}\end{frame}\end{document}`);const kinds=(r.presentation.slides[0]?.children??[]).filter(n=>n.type==="container").map(n=>n.kind);expect(kinds).toEqual(["fit-text","hstack","vstack","stretch","frame"]);});
  it("compiles mermaid diagrams into renderer-neutral IR",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{D}\begin{mermaid}graph LR
  A --> B
\end{mermaid}\end{frame}\end{document}`);const diagram=r.presentation.slides[0]?.children.find(n=>n.type==="diagram");expect(diagram).toMatchObject({type:"diagram",kind:"mermaid"});expect(diagram?.type==="diagram"&&diagram.code).toContain("A --> B");});
  it("propagates vertical section transitions onto the stack",()=>{const r=compile(String.raw`\begin{document}\begin{section}[transition=convex,transition-speed=fast]{Deep}\begin{frame}{A}A\end{frame}\end{section}\end{document}`);expect(r.presentation.navigation[0]).toMatchObject({type:"slide-stack",transition:{effect:"convex",speed:"fast"}});});
  it("understands beamer frame options",()=>{const r=compile(String.raw`\begin{document}\begin{frame}[label=intro,c,noframenumbering,fragile]{Intro}\begin{verbatim}x\end{verbatim}\end{frame}\end{document}`);const slide=r.presentation.slides[0];expect(slide?.id).toBe("intro");expect(slide?.center).toBe(true);expect(slide?.attributes["data-visibility"]).toBe("uncounted");expect(slide?.attributes["data-fragile"]).toBeUndefined();expect(slide?.attributes["data-c"]).toBeUndefined();});
  it("supports formatting aliases and includegraphics",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{F}\em{hi}\texttt{code}\includegraphics[width=50%]{img.png}\end{frame}\end{document}`);const children=r.presentation.slides[0]?.children??[];const formats=children.flatMap(function find(n):any[]{return n.type==="format"?[n]:"children" in n?n.children.flatMap(find):[];});expect(formats[0]).toMatchObject({style:"emph"});expect(formats[1]).toMatchObject({style:"texttt"});const image=children.find(n=>n.type==="image");expect(image).toMatchObject({type:"image",src:"img.png"});});
  it("repeats a labelled frame with \\againframe",()=>{const r=compile(String.raw`\begin{document}\begin{frame}[label=key]{Key}Body\end{frame}\begin{frame}{Other}O\end{frame}\againframe{key}\end{document}`);expect(r.presentation.slides).toHaveLength(3);const clone=r.presentation.slides[2];expect(clone?.id).toBe("key-again-2");expect(clone?.title?.[0]).toMatchObject({type:"text",value:"Key"});});
  it("ignores common beamer preamble commands",()=>{const r=compile(String.raw`\documentclass[aspectratio=169]{beamer}\usetheme{Berlin}\usepackage{amsmath}\setbeamertemplate{footline}{}\begin{document}\begin{frame}{A}A\end{frame}\end{document}`);expect(r.diagnostics).toEqual([]);});
  it("compiles description lists",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{D}\begin{description}\item[Term] Definition\end{description}\end{frame}\end{document}`);const list=r.presentation.slides[0]?.children.find(n=>n.type==="list");expect(list).toMatchObject({type:"list",description:true});expect(list?.type==="list"&&list.items[0]?.label).toBe("Term");});
  it("compiles lstinputlisting into a code node with src",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{L}\lstinputlisting[language=ts]{src/app.ts}\end{frame}\end{document}`,{file:"deck.rtex"});const c=r.presentation.slides[0]?.children.find(n=>n.type==="code");expect(c).toMatchObject({type:"code",src:"src/app.ts",language:"ts"});expect(r.presentation.assets).toContainEqual(expect.objectContaining({kind:"data",path:"src/app.ts"}));});
  it("records a logo asset",()=>{const r=compile(String.raw`\title{D}\logo{assets/logo.svg}\begin{document}\maketitle\begin{frame}{A}A\end{frame}\end{document}`,{file:"deck.rtex"});expect(r.presentation.metadata.logo).toBe("assets/logo.svg");expect(r.presentation.assets).toContainEqual(expect.objectContaining({kind:"image",path:"assets/logo.svg"}));});
  it("adds a title graphic to the title slide",()=>{const r=compile(String.raw`\title{D}\titlegraphic{assets/logo.svg}\begin{document}\maketitle\end{document}`,{file:"deck.rtex"});expect(r.presentation.metadata.titlegraphic).toBe("assets/logo.svg");expect(r.presentation.assets).toContainEqual(expect.objectContaining({kind:"image",path:"assets/logo.svg"}));expect(JSON.stringify(r.presentation.slides[0]?.children)).toContain("assets/logo.svg");});
  it("merges \\reveal source options",()=>{const r=compile(String.raw`\reveal{autoAnimate=true,transition=none}\begin{document}\begin{frame}{A}A\end{frame}\end{document}`);expect(r.presentation.configuration.reveal).toMatchObject({autoAnimate:true,transition:"none"});});
  it("resolves insertframenumber/inserttotalframenumber",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{A}\insertframenumber\end{frame}\begin{frame}{B}\insertframenumber/\inserttotalframenumber\end{frame}\end{document}`);expect(JSON.stringify(r.presentation.slides[0])).toContain('"value":"1"');expect(JSON.stringify(r.presentation.slides[1])).toContain('"value":"2"');});
  it("resolves \\label/\\ref to slide numbers",()=>{const r=compile(String.raw`\begin{document}\begin{frame}[label=first]{First}A\end{frame}\begin{frame}{Second}\label{second}B\end{frame}\begin{frame}{Third}See \ref{first} and \ref{second} and \ref{missing}.\end{frame}\end{document}`);const third=JSON.stringify(r.presentation.slides[2]);expect(third).toContain('"value":"1"');expect(third).toContain('"value":"2"');expect(third).toContain('"value":"missing"');});
  it("applies a default overlay specification to lists",()=>{const r=compile(String.raw`\beamerdefaultoverlayspecification{<+->}\begin{document}\begin{frame}{D}\begin{itemize}\item A\item B\end{itemize}\end{frame}\end{document}`);const list=r.presentation.slides[0]?.children.find(n=>n.type==="list");expect(list?.type==="list"&&list.items.map(i=>i.index)).toEqual([1,2]);});
  it("accepts starred commands",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{S}A\vspace*{1cm}B\end{frame}\end{document}`);const container=(r.presentation.slides[0]?.children??[]).find(n=>n.type==="container");expect(container).toMatchObject({kind:"vspace",options:{size:"1cm"}});});
  it("compiles vspace and hspace",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{S}A\vspace{1cm}\hspace{2em}B\end{frame}\end{document}`);const containers=(r.presentation.slides[0]?.children??[]).filter(n=>n.type==="container");expect(containers[0]).toMatchObject({kind:"vspace",options:{size:"1cm"}});expect(containers[1]).toMatchObject({kind:"hspace",options:{size:"2em"}});});
  it("supports overlay environments",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{E}\begin{onlyenv}<2->Only\end{onlyenv}\begin{visibleenv}<1-3>Visible\end{visibleenv}\end{frame}\end{document}`);const frags=(r.presentation.slides[0]?.children??[]).filter(n=>n.type==="fragment");expect(frags[0]).toMatchObject({only:true,start:2,index:1});expect(JSON.stringify(frags[0])).toContain("Only");expect(frags[1]).toMatchObject({start:1,end:3});});
  it("supports \\frametitle inside a frame",()=>{const r=compile(String.raw`\begin{document}\begin{frame}\frametitle{Dynamic title}Body\end{frame}\end{document}`);const slide=r.presentation.slides[0];expect(slide?.title?.[0]).toMatchObject({type:"text",value:"Dynamic title"});expect(JSON.stringify(slide?.children)).not.toContain("Dynamic title");});
  it("resolves component aliases",()=>{const aliasConfig={components:{MetricCard:{source:"@/M.vue",props:{value:{type:"number" as const,required:true}}}},aliases:{Score:"MetricCard"}};const r=compile(String.raw`\begin{document}\begin{frame}{A}\Score[value=1]\end{frame}\end{document}`,{config:aliasConfig});expect(r.diagnostics).toEqual([]);const component=r.presentation.slides[0]?.children.find(n=>n.type==="component");expect(component).toMatchObject({type:"component",name:"MetricCard",props:{value:1}});});
  it("keeps raw environment bodies that start with argument-like characters",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{C}\begin{chart}[type=bar]{ "labels": [] }
\end{chart}\begin{code}{not an arg}\end{code}\end{frame}\end{document}`);const chart=r.presentation.slides[0]?.children.find(n=>n.type==="diagram");expect(chart?.type==="diagram"&&chart.code).toContain('"labels"');const code=r.presentation.slides[0]?.children.find(n=>n.type==="code");expect(code?.type==="code"&&code.code).toBe("{not an arg}");});
  it("compiles chart blocks",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{C}\begin{chart}[type=line]{ "labels": ["A","B"], "datasets": [{ "data": [1,2] }] }\end{chart}\end{frame}\end{document}`);const diagram=r.presentation.slides[0]?.children.find(n=>n.type==="diagram");expect(diagram).toMatchObject({type:"diagram",kind:"chart",options:{type:"line"}});});
  it("supports hyperlink cross-slide links",()=>{const r=compile(String.raw`\begin{document}\begin{frame}[label=intro]{Intro}A\end{frame}\begin{frame}{B}\hyperlink{intro}{Back}\end{frame}\end{document}`);const links=(r.presentation.slides[1]?.children??[]).flatMap(function find(n):any[]{return n.type==="link"?[n]:"children" in n?n.children.flatMap(find):[];});expect(links[0]).toMatchObject({href:"#/intro"});});
  it("supports non-contiguous overlay windows",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{W}\only<2,4>{X}\visible<1,3>{Y}\end{frame}\end{document}`);const frags=(r.presentation.slides[0]?.children??[]).filter(n=>n.type==="fragment");expect(frags[0]).toMatchObject({only:true,index:1,start:2,windows:[{start:2,end:2},{start:4,end:4}]});expect(frags[1]?.windows).toEqual([{start:1,end:1},{start:3,end:3}]);});
  it("collects footnotes per frame",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{F}A\footnote{First}b\footnote{Second}c\end{frame}\end{document}`);const children=r.presentation.slides[0]?.children??[];const container=children.find(n=>n.type==="container"&&n.kind==="footnotes");expect(container).toBeTruthy();expect(container?.type==="container"&&container.children).toHaveLength(2);const refs=children.flatMap(function find(n):any[]{return n.type==="format"&&n.style==="footnote"?[n]:"children" in n?n.children.flatMap(find):[];});expect(refs).toHaveLength(2);});
  it("resolves relative (+-) overlay specs",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{R}\begin{itemize}\item<+-> One\item<+-> Two\end{itemize}\only<+->{Three}\end{frame}\end{document}`);const children=r.presentation.slides[0]?.children??[];const list=children.find(n=>n.type==="list");expect(list?.type==="list"&&list.items.map(i=>i.index)).toEqual([1,2]);const only=children.find(n=>n.type==="fragment");expect(only).toMatchObject({index:3,start:4,only:true});});
  it("compiles markdown blocks into markdown IR",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{M}\begin{markdown}# Title
- a
- b
\end{markdown}\end{frame}\end{document}`);const md=r.presentation.slides[0]?.children.find(n=>n.type==="markdown");expect(md?.type==="markdown"&&md.content).toContain("# Title");});
  it("supports verbatim, textcolor, and institute metadata",()=>{const r=compile(String.raw`\documentclass{reveal}\institute{Labs}\begin{document}\begin{frame}{V}\begin{verbatim}
a = 1
  b = 2
\end{verbatim}\textcolor{red}{hot}\end{frame}\end{document}`);expect(r.presentation.metadata.institute).toBe("Labs");const code=r.presentation.slides[0]?.children.find(n=>n.type==="code");expect(code?.type==="code"&&code.code).toBe("a = 1\n  b = 2");const formats=(r.presentation.slides[0]?.children??[]).flatMap(function find(n):any[]{return n.type==="format"?[n]:"children" in n?n.children.flatMap(find):[];});expect(formats[0]).toMatchObject({style:"textcolor",options:{color:"red"}});});
  it("accepts \\titlepage as a maketitle alias",()=>{const r=compile(String.raw`\title{D}\begin{document}\titlepage\begin{frame}{A}A\end{frame}\end{document}`);expect(r.presentation.slides[0]?.options.titleSlide).toBe(true);});
  it("lists frames with tableofcontents[frames]",()=>{const r=compile(String.raw`\title{D}\begin{document}\maketitle\tableofcontents[frames]\section{One}\begin{frame}{Alpha}A\end{frame}\begin{frame}{Beta}B\end{frame}\end{document}`);const toc=r.presentation.slides.find(s=>s.id==="table-of-contents");const list=toc?.children.find(n=>n.type==="list");expect(list?.type==="list"&&list.items).toHaveLength(2);expect(JSON.stringify(toc)).toContain("Alpha");});
  it("extracts frame subtitles and generates a table of contents",()=>{const r=compile(String.raw`\title{Deck}\begin{document}\maketitle\tableofcontents\section{One}\begin{frame}{Alpha}\framesubtitle{Sub}A\end{frame}\section{Two}\begin{frame}{Beta}B\end{frame}\end{document}`);const alpha=r.presentation.slides.find(s=>s.title?.some(n=>n.type==="text"&&n.value==="Alpha"));expect(alpha?.subtitle?.[0]).toMatchObject({type:"text",value:"Sub"});const toc=r.presentation.slides.find(s=>s.id==="table-of-contents");expect(toc).toBeTruthy();const list=toc?.children.find(n=>n.type==="list");expect(list?.type==="list"&&list.items).toHaveLength(2);expect(JSON.stringify(toc)).toContain("#/slide-");});
  it("maps alignment and quote environments",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{A}\begin{center}Mid\end{center}\begin{quote}Words\end{quote}\end{frame}\end{document}`);const kinds=(r.presentation.slides[0]?.children??[]).filter(n=>n.type==="container").map(n=>n.kind);expect(kinds).toEqual(["align-center","quote"]);});
  it("maps beamer block and theorem environments to titled containers",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{B}\begin{block}{Idea}Body\end{block}\begin{theorem}True.\end{theorem}\end{frame}\end{document}`);const containers=(r.presentation.slides[0]?.children??[]).filter(n=>n.type==="container");expect(containers[0]).toMatchObject({kind:"block",options:{title:"Idea"}});expect(containers[1]).toMatchObject({kind:"theorem"});});
  it("expands incremental list overlays",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{I}\begin{itemize}[<+->]\item One\item Two\item Three\end{itemize}\end{frame}\end{document}`);const list=r.presentation.slides[0]?.children.find(n=>n.type==="list");expect(list?.type==="list"&&list.items.map(i=>i.index)).toEqual([1,2,3]);});
  it("groups itemized notes into a list",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{N}\note[item]{First}\note[item]{Second}\end{frame}\end{document}`);const notes=r.presentation.slides[0]?.notes;expect(notes?.[0]).toMatchObject({type:"list"});expect(notes?.[0]?.type==="list"&&notes[0].items).toHaveLength(2);});
  it("supports column overlays",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{C}\begin{columns}\column<2->{0.5}A\end{columns}\end{frame}\end{document}`);const columns=r.presentation.slides[0]?.children.find(n=>n.type==="columns");expect(columns?.type==="columns"&&columns.columns[0]).toMatchObject({width:"0.5",index:1,start:2});});
  it("reads column vertical alignment",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{C}\begin{columns}\column[t]{0.5}A\end{columns}\end{frame}\end{document}`);const columns=r.presentation.slides[0]?.children.find(n=>n.type==="columns");expect(columns?.type==="columns"&&columns.columns[0]).toMatchObject({width:"0.5",align:"t"});});
  it("joins multiple authors with \\and",()=>{const r=compile(String.raw`\author{Ada \and Grace}\begin{document}\end{document}`);expect(r.presentation.metadata.author).toBe("Ada, Grace");});
  it("supports superscript and subscript",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{F}\textsuperscript{2}\textsubscript{i}\end{frame}\end{document}`);const formats=(r.presentation.slides[0]?.children??[]).flatMap(function find(n):any[]{return n.type==="format"?[n]:"children" in n?n.children.flatMap(find):[];});expect(formats.map(f=>f.style)).toEqual(["textsuperscript","textsubscript"]);});
  it("maps skip commands to spacers",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{S}A\bigskip B\end{frame}\end{document}`);const container=(r.presentation.slides[0]?.children??[]).find(n=>n.type==="container");expect(container).toMatchObject({kind:"vspace",options:{size:"1.5em"}});});
  it("compiles text line breaks",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{A\\B}C\end{frame}\end{document}`);expect(JSON.stringify(r.presentation.slides[0]?.title)).toContain('"linebreak"');});
  it("compiles email links",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{E}\email{a@b.com}\end{frame}\end{document}`);const link=(r.presentation.slides[0]?.children??[]).flatMap(function find(n):any[]{return n.type==="link"?[n]:"children" in n?n.children.flatMap(find):[];})[0];expect(link).toMatchObject({href:"mailto:a@b.com"});});
  it("parses per-row table overlays",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{T}\begin{table}[header=true]H1 & H2 \\ \only<2-> a & b \\ \end{table}\end{frame}\end{document}`);const t=r.presentation.slides[0]?.children.find(n=>n.type==="table");expect(t?.type==="table"&&t.rows).toEqual([["H1","H2"],["a","b"]]);expect(t?.type==="table"&&t.windows?.[1]).toEqual([{start:2}]);});
  it("ignores table rule commands",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{T}\begin{table}[header=true]\hline Name & Score \\ \hline Ada & 42 \\ \hline\end{table}\end{frame}\end{document}`);const t=r.presentation.slides[0]?.children.find(n=>n.type==="table");expect(t?.type==="table"&&t.rows).toEqual([["Name","Score"],["Ada","42"]]);});
  it("compiles tables and links",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{T}\begin{table}[header=true,caption={Scores}]Name & Score \\ Ada & 42 \\ \end{table}\href{https://revealjs.com}{Reveal}\url{https://example.com}\end{frame}\end{document}`);const table=r.presentation.slides[0]?.children.find(n=>n.type==="table");expect(table).toMatchObject({type:"table",header:true,caption:"Scores"});expect(table?.type==="table"&&table.rows).toEqual([["Name","Score"],["Ada","42"]]);const links=(r.presentation.slides[0]?.children??[]).flatMap(function find(n):any[]{return n.type==="link"?[n]:"children" in n?n.children.flatMap(find):[];});expect(links[0]).toMatchObject({href:"https://revealjs.com"});expect(links[1]?.type==="link"&&links[1].children[0]).toMatchObject({type:"text",value:"https://example.com"});});
  it("supports highlight step syntax and background video",()=>{const r=compile(String.raw`\begin{document}\begin{frame}[background-video=bg.mp4]{C}\begin{code}[language=ts,highlight={1|2|3}]one
two\end{code}\end{frame}\end{document}`);const slide=r.presentation.slides[0];expect(slide?.background?.video).toBe("bg.mp4");const c=slide?.children.find(n=>n.type==="code");expect(c?.type==="code"&&c.options.highlight).toBe("1|2|3");});
});
