import { describe, expect, it } from "vitest";
import { compile, parse, parseOptions, RevealTeXError } from "../src/index.js";

const config = { components: { MetricCard: { source: "@/MetricCard.vue", props: { value: { type: "number" as const, required: true }, label: { type: "string" as const, required: true } } }, DataChart: { source: "@/DataChart.vue", props: { data: { type: "asset" as const, required: true } } }, FeatureCard: { source: "@/FeatureCard.vue" } } };
describe("parser", () => {
  it("parses nested arguments and preserves locations", () => { const ast=parse("\\fragment{a \\textbf{nested} value}","deck.rtex"); const fragment=ast.children[0]; expect(fragment?.type).toBe("command"); expect(fragment?.location.start).toEqual({line:1,column:1,offset:0}); if(fragment?.type==="command") expect(fragment.requiredArguments[0]?.children[1]?.type).toBe("command"); });
  it("ignores comments but preserves escaped percent",()=>{const ast=parse("hello % gone\n94.7\\%");expect(ast.children.filter(n=>n.type==="text").map(n=>n.value).join("")).toContain("94.7%");expect(JSON.stringify(ast)).not.toContain("gone");});
  it("reports unclosed environments",()=>expect(()=>parse("\\begin{frame}x","x.rtex")).toThrow(RevealTeXError));
  it("parses structured options",()=>expect(parseOptions("value=94.7,label={Validation, Accuracy},active=true")).toEqual({value:94.7,label:"Validation, Accuracy",active:true}));
});
describe("semantic compilation",()=>{
  it("compiles slides, fragments, lists, math and components",()=>{const result=compile(String.raw`\documentclass{reveal}
\title{Demo}\date{August 2026}\transition{slide}\begin{document}\maketitle
\begin{frame}[id=results,transition=zoom]{Results}
\begin{itemize}\item<1-> First\item<2-> Second\end{itemize}
\[x^2\]\MetricCard[value=42,label={Users}]\end{frame}\end{document}`,{file:"deck.rtex",config});expect(result.diagnostics).toEqual([]);expect(result.presentation.slides).toHaveLength(2);expect(result.presentation.slides[0]?.children).toContainEqual(expect.objectContaining({type:"format",style:"date"}));expect(result.presentation.slides[1]).toMatchObject({id:"results",transition:{effect:"zoom"}});expect(JSON.stringify(result.presentation)).toContain('"MetricCard"');const list=result.presentation.slides[1]?.children.find(n=>n.type==="list");expect(list?.type==="list"&&list.items.map(i=>i.index)).toEqual([undefined,1]);});
  it("validates component props",()=>{const result=compile(String.raw`\begin{document}\begin{frame}{X}\MetricCard[value={oops}]\end{frame}\end{document}`,{config});expect(result.diagnostics.some(d=>d.code==="RTX3003")).toBe(true);expect(result.diagnostics.some(d=>d.code==="RTX3001")).toBe(true);});
  it("records typed component assets in the renderer-independent manifest",()=>{const result=compile(String.raw`\begin{document}\begin{frame}{X}\DataChart[data={data/results.json}]\end{frame}\end{document}`,{file:"slides/results.rtex",config});expect(result.diagnostics).toEqual([]);expect(result.presentation.assets).toContainEqual(expect.objectContaining({kind:"data",path:"data/results.json",source:expect.objectContaining({file:"slides/results.rtex"})}));});
  it("turns pause boundaries into staged trailing content",()=>{const result=compile(String.raw`\begin{document}\begin{frame}{Sequence}Always visible.\pause Second step.\pause Third step.\end{frame}\end{document}`);const children=result.presentation.slides[0]?.children??[];expect(children[0]).toMatchObject({type:"paragraph"});expect(children[1]).toMatchObject({type:"fragment",index:1});expect(children[2]).toMatchObject({type:"fragment",index:2});expect(JSON.stringify(children)).not.toContain("__revealtex_pause_boundary__");});
  it("maps plugin commands and environments to validated component IR",()=>{const plugin={name:"domain",components:{PluginMetric:{source:"@/PluginMetric.vue",props:{value:{type:"number" as const,required:true},label:{type:"string" as const}}},PluginPanel:{source:"@/PluginPanel.vue"}},commands:{metric:{component:"PluginMetric",props:({argument}:{argument?:string})=>({value:Number(argument),label:"Score"})}},environments:{panel:{component:"PluginPanel"}}};const result=compile(String.raw`\begin{document}\begin{frame}{Plugin}\metric{94.7}\begin{panel}[tone=quiet]Nested content.\end{panel}\end{frame}\end{document}`,{config:{plugins:[plugin]}});expect(result.diagnostics).toEqual([]);const components=result.presentation.slides[0]?.children.filter(node=>node.type==="component")??[];expect(components[0]).toMatchObject({type:"component",name:"PluginMetric",props:{value:94.7,label:"Score"},children:[]});expect(components[1]).toMatchObject({type:"component",name:"PluginPanel",props:{tone:"quiet"}});expect(JSON.stringify(components[1])).toContain("Nested content.");});
  it("normalizes visual and positioning containers",()=>{const result=compile(String.raw`\begin{document}\begin{frame}{Containers}\card{Card}\callout[info]{Notice}\badge{Beta}\position[x=12,y=20,width=40]{Placed}\end{frame}\end{document}`);expect(result.diagnostics).toEqual([]);expect(result.presentation.slides[0]?.children).toEqual(expect.arrayContaining([expect.objectContaining({type:"container",kind:"card"}),expect.objectContaining({type:"container",kind:"callout",options:{variant:"info"}}),expect.objectContaining({type:"container",kind:"badge"}),expect.objectContaining({type:"container",kind:"position",options:{x:12,y:20,width:40}})]));});
  it("extracts named component slots",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{X}\begin{FeatureCard}\slot{title}{Fast}Body\end{FeatureCard}\end{frame}\end{document}`,{config});const component=r.presentation.slides[0]?.children.find(n=>n.type==="component");expect(component?.type).toBe("component");if(component?.type==="component"){expect(component.slots.title?.[0]?.type).toBe("paragraph");expect(JSON.stringify(component.slots.title)).toContain("Fast");}});
  it("normalizes paragraphs, backgrounds, and optional section dividers",()=>{const r=compile(String.raw`\begin{document}\section{Results}\begin{frame}[background=#10131c]{X}\backgroundgradient{linear-gradient(#111,#222)}First paragraph.

Second paragraph.\end{frame}\end{document}`,{config:{...config,sections:{autoDividerSlides:true}}});expect(r.presentation.slides).toHaveLength(2);expect(r.presentation.slides[0]?.options.sectionDivider).toBe(true);expect(r.presentation.slides[1]?.background).toEqual({color:"#10131c",image:undefined,gradient:"linear-gradient(#111,#222)"});expect(r.presentation.slides[1]?.children.filter(n=>n.type==="paragraph")).toHaveLength(2);});
  it("represents vertical sections without renderer concepts",()=>{const r=compile(String.raw`\begin{document}\begin{section}{Deep Dive}\begin{frame}{Overview}A\end{frame}\begin{subframe}{Detail}B\end{subframe}\end{section}\end{document}`);expect(r.diagnostics).toEqual([]);expect(r.presentation.slides).toHaveLength(2);expect(r.presentation.navigation).toHaveLength(1);expect(r.presentation.navigation[0]).toMatchObject({type:"slide-stack",title:"Deep Dive"});expect(JSON.stringify(r.presentation.navigation)).not.toContain("Vue");});
});
describe("reveal feature coverage",()=>{
  it("maps beamer-style overlay commands and list items onto overlay numbers",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{O}\only<2->{Two}\uncover<3>{Three}\visible<1-2>{Early}\alt<2>{A}{B}\begin{itemize}\item<1-> One\item<3-> Three\end{itemize}\end{frame}\end{document}`);expect(r.diagnostics).toEqual([]);const children=r.presentation.slides[0]?.children??[];const fragments=children.filter(n=>n.type==="fragment");expect(fragments[0]).toMatchObject({only:true,start:2,index:1});expect(fragments[1]).toMatchObject({start:3,end:3,index:2});expect(fragments[2]).toMatchObject({start:1,end:2});expect(fragments[3]).toMatchObject({start:1,end:1});expect(fragments[4]).toMatchObject({start:2,index:1});const list=children.find(n=>n.type==="list");expect(list?.type==="list"&&list.items[0]?.index).toBeUndefined();expect(list?.type==="list"&&list.items[1]).toMatchObject({index:2,start:3});});
  it("supports dollar display math and amsmath environments",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{M}$$a=b$$\begin{align}a&=b\\c&=d\end{align}\begin{equation}e=f\end{equation}\begin{gather}g=h\end{gather}\end{frame}\end{document}`);const math=(r.presentation.slides[0]?.children??[]).filter(n=>n.type==="math");expect(math[0]).toMatchObject({display:true,tex:"a=b"});expect(math[1]).toMatchObject({display:true});expect(math[1]?.tex).toContain("\\begin{align}");expect(math[2]).toMatchObject({display:true,tex:"e=f"});expect(math[3]?.tex).toContain("\\begin{gather}");});
  it("passes reveal frame options through, resolves today, and records backgrounds and themes",()=>{const r=compile(String.raw`\documentclass{reveal}\title{D}\date{\today}\theme{dracula}\begin{document}\begin{frame}[state=intro,background-video=bg.mp4,background-size=cover,background-opacity=0.5,autoslide=4000]{X}Body\end{frame}\end{document}`,{file:"deck.rtex"});const slide=r.presentation.slides[0];expect(r.presentation.configuration.theme).toBe("dracula");expect(r.presentation.metadata.date).not.toContain("\\today");expect(slide?.background).toMatchObject({video:"bg.mp4",size:"cover",opacity:"0.5"});expect(slide?.attributes).toMatchObject({"data-state":"intro","data-autoslide":"4000"});expect(slide?.attributes["data-background-video"]).toBeUndefined();});
  it("compiles reveal layout utility containers",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{U}\fittext{Big}\hstack{A}\vstack{B}\stretch{C}\frame{D}\end{frame}\end{document}`);const kinds=(r.presentation.slides[0]?.children??[]).filter(n=>n.type==="container").map(n=>n.kind);expect(kinds).toEqual(["fit-text","hstack","vstack","stretch","frame"]);});
  it("compiles mermaid diagrams into renderer-neutral IR",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{D}\begin{mermaid}graph LR
  A --> B
\end{mermaid}\end{frame}\end{document}`);const diagram=r.presentation.slides[0]?.children.find(n=>n.type==="diagram");expect(diagram).toMatchObject({type:"diagram",kind:"mermaid"});expect(diagram?.type==="diagram"&&diagram.code).toContain("A --> B");});
  it("propagates vertical section transitions onto the stack",()=>{const r=compile(String.raw`\begin{document}\begin{section}[transition=convex,transition-speed=fast]{Deep}\begin{frame}{A}A\end{frame}\end{section}\end{document}`);expect(r.presentation.navigation[0]).toMatchObject({type:"slide-stack",transition:{effect:"convex",speed:"fast"}});});
  it("understands beamer frame options",()=>{const r=compile(String.raw`\begin{document}\begin{frame}[label=intro,c,noframenumbering,fragile]{Intro}\begin{verbatim}x\end{verbatim}\end{frame}\end{document}`);const slide=r.presentation.slides[0];expect(slide?.id).toBe("intro");expect(slide?.center).toBe(true);expect(slide?.attributes["data-visibility"]).toBe("uncounted");expect(slide?.attributes["data-fragile"]).toBeUndefined();expect(slide?.attributes["data-c"]).toBeUndefined();});
  it("supports formatting aliases and includegraphics",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{F}\em{hi}\texttt{code}\includegraphics[width=50%]{img.png}\end{frame}\end{document}`);const children=r.presentation.slides[0]?.children??[];const formats=children.flatMap(function find(n):any[]{return n.type==="format"?[n]:"children" in n?n.children.flatMap(find):[];});expect(formats[0]).toMatchObject({style:"emph"});expect(formats[1]).toMatchObject({style:"texttt"});const image=children.find(n=>n.type==="image");expect(image).toMatchObject({type:"image",src:"img.png"});});
  it("collects footnotes per frame",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{F}A\footnote{First}b\footnote{Second}c\end{frame}\end{document}`);const children=r.presentation.slides[0]?.children??[];const container=children.find(n=>n.type==="container"&&n.kind==="footnotes");expect(container).toBeTruthy();expect(container?.type==="container"&&container.children).toHaveLength(2);const refs=children.flatMap(function find(n):any[]{return n.type==="format"&&n.style==="footnote"?[n]:"children" in n?n.children.flatMap(find):[];});expect(refs).toHaveLength(2);});
  it("resolves relative (+-) overlay specs",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{R}\begin{itemize}\item<+-> One\item<+-> Two\end{itemize}\only<+->{Three}\end{frame}\end{document}`);const children=r.presentation.slides[0]?.children??[];const list=children.find(n=>n.type==="list");expect(list?.type==="list"&&list.items.map(i=>i.index)).toEqual([1,2]);const only=children.find(n=>n.type==="fragment");expect(only).toMatchObject({index:3,start:4,only:true});});
  it("compiles markdown blocks into markdown IR",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{M}\begin{markdown}# Title
- a
- b
\end{markdown}\end{frame}\end{document}`);const md=r.presentation.slides[0]?.children.find(n=>n.type==="markdown");expect(md?.type==="markdown"&&md.content).toContain("# Title");});
  it("supports verbatim, textcolor, and institute metadata",()=>{const r=compile(String.raw`\documentclass{reveal}\institute{Labs}\begin{document}\begin{frame}{V}\begin{verbatim}
a = 1
  b = 2
\end{verbatim}\textcolor{red}{hot}\end{frame}\end{document}`);expect(r.presentation.metadata.institute).toBe("Labs");const code=r.presentation.slides[0]?.children.find(n=>n.type==="code");expect(code?.type==="code"&&code.code).toBe("a = 1\n  b = 2");const formats=(r.presentation.slides[0]?.children??[]).flatMap(function find(n):any[]{return n.type==="format"?[n]:"children" in n?n.children.flatMap(find):[];});expect(formats[0]).toMatchObject({style:"textcolor",options:{color:"red"}});});
  it("extracts frame subtitles and generates a table of contents",()=>{const r=compile(String.raw`\title{Deck}\begin{document}\maketitle\tableofcontents\section{One}\begin{frame}{Alpha}\framesubtitle{Sub}A\end{frame}\section{Two}\begin{frame}{Beta}B\end{frame}\end{document}`);const alpha=r.presentation.slides.find(s=>s.title?.some(n=>n.type==="text"&&n.value==="Alpha"));expect(alpha?.subtitle?.[0]).toMatchObject({type:"text",value:"Sub"});const toc=r.presentation.slides.find(s=>s.id==="table-of-contents");expect(toc).toBeTruthy();const list=toc?.children.find(n=>n.type==="list");expect(list?.type==="list"&&list.items).toHaveLength(2);expect(JSON.stringify(toc)).toContain("#/slide-");});
  it("maps alignment and quote environments",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{A}\begin{center}Mid\end{center}\begin{quote}Words\end{quote}\end{frame}\end{document}`);const kinds=(r.presentation.slides[0]?.children??[]).filter(n=>n.type==="container").map(n=>n.kind);expect(kinds).toEqual(["align-center","quote"]);});
  it("maps beamer block and theorem environments to titled containers",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{B}\begin{block}{Idea}Body\end{block}\begin{theorem}True.\end{theorem}\end{frame}\end{document}`);const containers=(r.presentation.slides[0]?.children??[]).filter(n=>n.type==="container");expect(containers[0]).toMatchObject({kind:"block",options:{title:"Idea"}});expect(containers[1]).toMatchObject({kind:"theorem"});});
  it("expands incremental list overlays",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{I}\begin{itemize}[<+->]\item One\item Two\item Three\end{itemize}\end{frame}\end{document}`);const list=r.presentation.slides[0]?.children.find(n=>n.type==="list");expect(list?.type==="list"&&list.items.map(i=>i.index)).toEqual([1,2,3]);});
  it("compiles tables and links",()=>{const r=compile(String.raw`\begin{document}\begin{frame}{T}\begin{table}[header=true,caption={Scores}]Name & Score \\ Ada & 42 \\ \end{table}\href{https://revealjs.com}{Reveal}\url{https://example.com}\end{frame}\end{document}`);const table=r.presentation.slides[0]?.children.find(n=>n.type==="table");expect(table).toMatchObject({type:"table",header:true,caption:"Scores"});expect(table?.type==="table"&&table.rows).toEqual([["Name","Score"],["Ada","42"]]);const links=(r.presentation.slides[0]?.children??[]).flatMap(function find(n):any[]{return n.type==="link"?[n]:"children" in n?n.children.flatMap(find):[];});expect(links[0]).toMatchObject({href:"https://revealjs.com"});expect(links[1]?.type==="link"&&links[1].children[0]).toMatchObject({type:"text",value:"https://example.com"});});
  it("supports highlight step syntax and background video",()=>{const r=compile(String.raw`\begin{document}\begin{frame}[background-video=bg.mp4]{C}\begin{code}[language=ts,highlight={1|2|3}]one
two\end{code}\end{frame}\end{document}`);const slide=r.presentation.slides[0];expect(slide?.background?.video).toBe("bg.mp4");const c=slide?.children.find(n=>n.type==="code");expect(c?.type==="code"&&c.options.highlight).toBe("1|2|3");});
});
