import type { ComponentDefinition, PresentationIR, PresentationNode, PropertyValue, RevealTeXConfig, SlideIR } from "@revealtex/compiler";
import { isRevealTheme } from "@revealtex/compiler";
import type { PresentationRenderer, RenderContext, RenderResult } from "@revealtex/renderer-core";
import { renderMarkdown } from "@revealtex/renderer-core";
import { dirname, resolve } from "node:path";

export class VueRenderer implements PresentationRenderer {
  readonly name = "vue";
  readonly capabilities = { fragments: true, transitions: true, autoAnimate: true, speakerNotes: true, customComponents: true, interactiveComponents: true, rawHtml: true, rendererSpecificBlocks: true };
  async render(presentation: PresentationIR, context: RenderContext): Promise<RenderResult> {
    const source = renderVue(presentation, context.config, context.sourceFile);
    const manifest = `// AUTO-GENERATED BY REVEALTEX. DO NOT EDIT.\nexport const presentationMetadata = ${JSON.stringify(presentation.metadata, null, 2)} as const;\nexport const sourceFiles = ${JSON.stringify(presentation.sourceFiles, null, 2)} as const;\n`;
    return { files: [{ path: "Presentation.generated.vue", content: source }, { path: "presentation.generated.ts", content: manifest }], diagnostics: [] };
  }
}

export function renderVue(presentation: PresentationIR, config: RevealTeXConfig = {}, sourceFile = "presentation.rtex"): string {
  const used = new Set<string>(); const layouts = new Set<string>(); const mediaBindings = new Map<string, string>(); const mediaImports: string[] = [];
  const components = mergedComponents(config);
  const registerAsset = (src: string, file: string) => { const path = resolvableAssetPath(src, file); if (!path) return; const key = assetKey(src, file); if (!mediaBindings.has(key)) { const name = `rtAsset${mediaBindings.size}`; mediaBindings.set(key, name); mediaImports.push(`import ${name} from ${JSON.stringify(path)};`); } };
  const visit = (nodes: PresentationNode[]) => { for (const n of nodes) { if (n.type === "image" || n.type === "video" || n.type === "svg") registerAsset(n.src, n.source.file); if (n.type === "component") { used.add(n.name); for (const [name, schema] of Object.entries(components[n.name]?.props ?? {})) { const value = n.props[name]; if (schema.type === "asset" && typeof value === "string") registerAsset(value, n.source.file); } visit(n.children); Object.values(n.slots).forEach(visit); } else if ("children" in n && Array.isArray(n.children)) visit(n.children); if (n.type === "columns") n.columns.forEach(c => visit(c.children)); if (n.type === "list") n.items.forEach(i => visit(i.children)); } };
  for (const slide of presentation.slides) { visit(slide.children); if (slide.layout) layouts.add(slide.layout); if (slide.background?.image) registerAsset(slide.background.image, slide.source.file); if (slide.background?.video) registerAsset(slide.background.video, slide.source.file); }
  const renderState: VueRenderState = { assetBindings: mediaBindings, components, markdown: new Map<string, string>() };
  const imports = [...used].sort().map(name => componentImport(name, components[name])).filter(Boolean);
  const layoutImports = [...layouts].sort().map(name => config.layouts?.[name] ? `import ${safeName(name)} from ${JSON.stringify(config.layouts[name]!.source)};` : "").filter(Boolean);
  const assetImports = [...new Set([
    ...presentation.configuration.stylesheets,
    ...(config.theme?.css ? [config.theme.css] : []),
    ...presentation.configuration.scripts
  ])].sort().map(path => `import ${JSON.stringify(resolveSourceImport(path, sourceFile))};`);
  const vueImports = [...used].some(name => components[name]?.lazy) ? 'import { defineAsyncComponent } from "vue";' : "";
  const themeName = presentation.configuration.theme ?? config.theme?.name;
  const themeImport = !config.theme?.css && isRevealTheme(themeName) ? `import ${JSON.stringify(`reveal.js/dist/theme/${themeName}.css`)};` : "";
  const revealOptions = { ...(config.reveal ?? {}), ...stripUndefined({ transition: presentation.configuration.transition, transitionSpeed: presentation.configuration.transitionSpeed, controls: presentation.configuration.controls, progress: presentation.configuration.progress, slideNumber: presentation.configuration.slideNumbers }) };
  const lines = presentation.navigation.map(item => item.type === "slide-stack"
    ? indent(`<section class="rt-slide-stack"${stackAttrs(item)}>\n${item.slides.map(slide => indent(renderSlide(slide, renderState), 2)).join("\n")}\n</section>`, 4)
    : indent(renderSlide(item, renderState), 4)).join("\n");
  const markdownDecls = [...renderState.markdown.entries()].map(([name, html]) => `const ${name} = ${JSON.stringify(html)};`).join("\n");
  return `<!-- AUTO-GENERATED BY REVEALTEX. DO NOT EDIT.\nSource: ${escapeComment(sourceFile)}\n-->\n<script setup lang="ts">\nimport { RevealDeck, RevealSlide, RevealFragment, RevealMath, RevealCode, RevealNotes, Mermaid } from "@revealtex/runtime-vue";\n${[vueImports, ...assetImports, themeImport, ...mediaImports, ...imports, ...layoutImports].filter(Boolean).join("\n")}\nconst revealOptions = ${serializeJs(stripUndefined(revealOptions))};\nconst mathMacros = ${serializeJs(presentation.configuration.mathMacros)};${markdownDecls ? "\n" + markdownDecls : ""}\n</script>\n\n<template>\n  <RevealDeck :options="revealOptions" :math-macros="mathMacros">\n${lines}\n  </RevealDeck>\n</template>\n`;
}

interface VueRenderState { assetBindings: Map<string, string>; components: Record<string, ComponentDefinition>; markdown: Map<string, string> }
function stackAttrs(stack: Extract<import("@revealtex/compiler").NavigationIR, { type: "slide-stack" }>): string {
  const parts: string[] = [];
  if (stack.transition?.effect) parts.push(`data-transition=${quote(stack.transition.effect)}`);
  if (stack.transition?.speed) parts.push(`data-transition-speed=${quote(stack.transition.speed)}`);
  for (const [name, value] of Object.entries(stack.attributes ?? {})) parts.push(value === "" ? name : `${name}=${quote(value)}`);
  return parts.length ? " " + parts.join(" ") : "";
}
function renderSlide(slide: SlideIR, state: VueRenderState): string {
  const attrs: string[] = [`id=${quote(slide.id)}`];
  if (slide.transition?.effect) attrs.push(`transition=${quote(slide.transition.effect)}`);
  if (slide.transition?.speed) attrs.push(`transition-speed=${quote(slide.transition.speed)}`);
  if (slide.autoAnimate) attrs.push("auto-animate"); if (slide.center) attrs.push("center");
  if (slide.background?.color) attrs.push(`background-color=${quote(slide.background.color)}`);
  if (slide.background?.image) attrs.push(assetAttribute("background-image", slide.background.image, slide.source.file, state.assetBindings));
  if (slide.background?.gradient) attrs.push(`background-gradient=${quote(slide.background.gradient)}`);
  if (slide.background?.video) attrs.push(assetAttribute("data-background-video", slide.background.video, slide.source.file, state.assetBindings));
  if (slide.background?.iframe) attrs.push(`data-background-iframe=${quote(slide.background.iframe)}`);
  if (slide.background?.size) attrs.push(`data-background-size=${quote(slide.background.size)}`);
  if (slide.background?.position) attrs.push(`data-background-position=${quote(slide.background.position)}`);
  if (slide.background?.repeat) attrs.push(`data-background-repeat=${quote(slide.background.repeat)}`);
  if (slide.background?.opacity !== undefined) attrs.push(`data-background-opacity=${quote(String(slide.background.opacity))}`);
  if (slide.background?.transition) attrs.push(`data-background-transition=${quote(slide.background.transition)}`);
  if (slide.background?.videoLoop) attrs.push("data-background-video-loop");
  if (slide.background?.videoMuted) attrs.push("data-background-video-muted");
  if (slide.background?.interactive) attrs.push("data-background-interactive");
  for (const [name, value] of Object.entries(slide.attributes)) attrs.push(value === "" ? name : `${name}=${quote(value)}`);
  const classes = [typeof slide.options.class === "string" ? slide.options.class : undefined, slide.options.titleSlide === true ? "rt-title-slide" : undefined, slide.options.sectionDivider === true ? "rt-section-divider" : undefined, slide.options.t === true ? "rt-top" : undefined, slide.options.b === true ? "rt-bottom" : undefined].filter(Boolean).join(" ");
  if (classes) attrs.push(`class=${quote(classes)}`);
  if (typeof slide.options.style === "string") attrs.push(`style=${quote(slide.options.style)}`);
  const title = slide.title?.length ? `<h2>${renderNodes(slide.title, state)}</h2>` : "";
  const subtitle = slide.subtitle?.length ? `<h3 class="rt-frame-subtitle">${renderNodes(slide.subtitle, state)}</h3>` : "";
  const content = `${subtitle}${renderNodes(slide.children, state)}${slide.notes?.length ? `<RevealNotes>${renderNodes(slide.notes, state)}</RevealNotes>` : ""}`;
  if (slide.layout) return `<RevealSlide ${attrs.join(" ")}>\n${indent(title, 2)}\n  <${safeName(slide.layout)}>${content}</${safeName(slide.layout)}>\n</RevealSlide>`;
  return `<RevealSlide ${attrs.join(" ")}>\n${indent(`${title}${content}`, 2)}\n</RevealSlide>`;
}
function renderNodes(nodes: PresentationNode[], state: VueRenderState): string { return nodes.map(node => renderNode(node, state)).join(""); }
function renderNode(node: PresentationNode, state: VueRenderState): string {
  switch (node.type) {
    case "text": return escapeHtml(node.value);
    case "paragraph": return `<p>${renderNodes(node.children, state)}</p>`;
    case "math": return `<RevealMath ${node.display ? "display " : ""}:tex=${quoteBinding(node.tex)} />`;
    case "format": {
      const color = typeof node.options?.color === "string" ? node.options.color : undefined;
      if (node.style === "footnote") return `<sup class="rt-footnote-ref">${renderNodes(node.children, state)}</sup>`;
      if (node.style === "footnote-marker") return `<sup class="rt-footnote-marker">${renderNodes(node.children, state)}</sup>`;
      if (node.style === "textcolor" && color) return `<span class="rt-textcolor" style=${quote(`color:${color}`)}>${renderNodes(node.children, state)}</span>`;
      if (node.style === "colorbox" && color) return `<span class="rt-colorbox" style=${quote(`background:${color}`)}>${renderNodes(node.children, state)}</span>`;
      return `<span class=${quote(`rt-${node.style}`)}>${renderNodes(node.children, state)}</span>`;
    }
    case "fragment": {
      const managed = node.index !== undefined || (node.start === undefined && node.end === undefined);
      if (managed) return `<RevealFragment${node.effect ? ` effect=${quote(node.effect)}` : ""}${node.index !== undefined ? ` :index=${quoteBinding(node.index)}` : ""}${node.only ? ' class="rt-only"' : ""}${overlayDataAttrs(node)}>${renderNodes(node.children, state)}</RevealFragment>`;
      const classes = ["rt-overlay", node.effect, node.only && "rt-only"].filter(Boolean).join(" ");
      return `<div class=${quote(classes)}${overlayDataAttrs(node)}>${renderNodes(node.children, state)}</div>`;
    }
    case "animation": return `<RevealFragment effect=${quote(node.effect)}${animationStyle(node)}>${renderNodes(node.children, state)}</RevealFragment>`;
    case "list": return `<${node.ordered ? "ol" : "ul"}>${node.items.map(item => renderNode(item, state)).join("")}</${node.ordered ? "ol" : "ul"}>`;
    case "list-item": {
      if (node.index === undefined && node.start === undefined && node.end === undefined) return `<li>${renderNodes(node.children, state)}</li>`;
      const classes = ["rt-overlay", node.index !== undefined && "fragment", node.only && "rt-only"].filter(Boolean).join(" ");
      const indexAttr = node.index !== undefined ? ` data-fragment-index=${quote(String(node.index))}` : "";
      return `<li class=${quote(classes)}${indexAttr}${overlayDataAttrs(node)}>${renderNodes(node.children, state)}</li>`;
    }
    case "columns": return `<div class="rt-columns"${columnStyle(node.gap, node.alignment)}>${node.columns.map(column => renderNode(column, state)).join("")}</div>`;
    case "column": return `<div class="rt-column"${node.width ? ` style=${quote(`flex-basis:${columnWidth(node.width)}`)}` : ""}>${renderNodes(node.children, state)}</div>`;
    case "image": return `<figure><img ${assetAttribute("src", node.src, node.source.file, state.assetBindings)}${attrs(node.options, ["alt"])}${mediaPresentationAttrs(node.options)} />${node.options.caption ? `<figcaption>${escapeHtml(String(node.options.caption))}</figcaption>` : ""}</figure>`;
    case "svg": return `<img ${assetAttribute("src", node.src, node.source.file, state.assetBindings)}${attrs(node.options, ["alt"])}${mediaPresentationAttrs(node.options, "rt-svg")} />`;
    case "video": return `<video ${assetAttribute("src", node.src, node.source.file, state.assetBindings)}${attrs(node.options, ["autoplay", "muted", "loop", "controls"])}${mediaPresentationAttrs(node.options)}></video>`;
    case "code": return `<RevealCode :code=${quoteBinding(node.code)}${node.language ? ` language=${quote(node.language)}` : ""}${attrs(node.options, ["numbers", "highlight"])} />`;
    case "diagram": return `<Mermaid kind=${quote(node.kind)} :code=${quoteBinding(node.code)} />`;
    case "markdown": { const name = `rtMarkdown${state.markdown.size}`; state.markdown.set(name, renderMarkdown(node.content)); return `<div class="rt-markdown" v-html=${quote(name)}></div>`; }
    case "link": return `<a href=${quote(node.href)} target="_blank" rel="noopener">${renderNodes(node.children, state)}</a>`;
    case "table": return renderTable(node);
    case "slot": return `<template #${safeName(node.name)}>${renderNodes(node.children, state)}</template>`;
    case "notes": return `<RevealNotes>${renderNodes(node.children, state)}</RevealNotes>`;
    case "element": return `<div${node.id ? ` data-id=${quote(node.id)}` : ""}>${renderNodes(node.children, state)}</div>`;
    case "container": { const tag=containerTag(node.kind);const heading=typeof node.options.title==="string"&&node.options.title?`<div class="rt-container__title">${escapeHtml(node.options.title)}</div>`:"";return `<${tag} class=${quote(containerClass(node.kind,node.options))}${containerStyle(node.kind,node.options)}>${heading}${renderNodes(node.children, state)}</${tag}>`; }
    case "renderer-specific": return node.renderer === "vue" || node.renderer === "html" ? node.content : "";
    case "component": { const slots = Object.entries(node.slots).map(([name, children]) => `<template #${safeName(name)}>${renderNodes(children, state)}</template>`).join(""); return `<${safeName(node.name)}${componentAttrs(node.name, node.props, node.source.file, state)}>${slots}${renderNodes(node.children, state)}</${safeName(node.name)}>`; }
  }
}
function componentAttrs(name: string, values: Record<string, PropertyValue>, file: string, state: VueRenderState): string { const schemas = state.components[name]?.props ?? {}; return Object.entries(values).map(([key, value]) => schemas[key]?.type === "asset" && typeof value === "string" ? ` ${assetAttribute(key, value, file, state.assetBindings)}` : attrs({ [key]: value })).join(""); }
function attrs(values: Record<string, PropertyValue>, only?: string[]): string { return Object.entries(values).filter(([k]) => !only || only.includes(k)).map(([key, value]) => value === true ? ` ${key}` : value === false ? ` :${key}="false"` : typeof value === "string" ? ` ${key}=${quote(value)}` : ` :${key}=${quoteBinding(value)}`).join(""); }
function renderTable(node: Extract<PresentationNode, { type: "table" }>): string {
  const head = node.header && node.rows.length ? node.rows[0]! : undefined;
  const body = node.header ? node.rows.slice(1) : node.rows;
  const caption = node.caption ? `<caption>${escapeHtml(node.caption)}</caption>` : "";
  const thead = head ? `<thead><tr>${head.map(cell => `<th>${escapeHtml(cell)}</th>`).join("")}</tr></thead>` : "";
  const tbody = `<tbody>${body.map(row => `<tr>${row.map(cell => `<td>${escapeHtml(cell)}</td>`).join("")}</tr>`).join("")}</tbody>`;
  return `<table class="rt-table">${caption}${thead}${tbody}</table>`;
}
function overlayDataAttrs(node: { index?: number; start?: number; end?: number }): string {
  const parts: string[] = [];
  const start = node.start ?? (node.index !== undefined ? node.index + 1 : undefined);
  if (start !== undefined) parts.push(`data-rt-overlay-start=${quote(String(start))}`);
  if (node.end !== undefined) parts.push(`data-rt-overlay-end=${quote(String(node.end))}`);
  return parts.length ? " " + parts.join(" ") : "";
}
function animationStyle(node: Extract<PresentationNode, { type: "animation" }>): string { const values = [node.duration && `--rt-duration:${node.duration}`, node.delay && `--rt-delay:${node.delay}`, node.easing && `--rt-easing:${node.easing}`].filter(Boolean); return values.length ? ` style=${quote(values.join(";"))}` : ""; }
function columnStyle(gap?: string, alignment?: string): string { const values = [gap && `gap:${gap}`, alignment && `align-items:${columnAlignment(alignment)}`].filter(Boolean); return values.length ? ` style=${quote(values.join(";"))}` : ""; }
function columnAlignment(value: string): string { return ({ top: "flex-start", start: "flex-start", middle: "center", center: "center", bottom: "flex-end", end: "flex-end" } as Record<string, string>)[value] ?? value; }
const REVEAL_UTILITY_CLASSES: Record<string,string> = { "fit-text":"r-fit-text", stack:"r-stack", hstack:"r-hstack", vstack:"r-vstack", stretch:"r-stretch", frame:"r-frame" };
function containerTag(kind:string):string{return kind==="badge"?"span":kind==="callout"?"aside":kind==="quote"?"blockquote":"div";}
function containerClass(kind:string,options:Record<string,PropertyValue>):string{const base=REVEAL_UTILITY_CLASSES[kind]??`rt-${kind.replace(":","-")}`;const variant=typeof options.variant==="string"?`${base}--${options.variant.replace(/[^a-z0-9_-]/gi,"-")}`:"";return[base,variant].filter(Boolean).join(" ");}
function containerStyle(kind:string,options:Record<string,PropertyValue>):string{if(kind!=="place"&&kind!=="position")return"";const positioned:Record<string,PropertyValue|undefined>=kind==="position"?{left:options.x,top:options.y,width:options.width,height:options.height}:{left:options.left,top:options.top,right:options.right,bottom:options.bottom,width:options.width,height:options.height};const declarations=["position:absolute",...Object.entries(positioned).filter(([,value])=>value!==undefined).map(([name,value])=>`${name}:${positionValue(value!)}`)];return` style=${quote(declarations.join(";"))}`;}
function positionValue(value:PropertyValue):string{return typeof value==="number"?`${value}%`:String(value);}
function componentImport(name: string, definition?: ComponentDefinition): string { const source = definition?.source ?? definition?.vue; if (!source) return ""; return definition?.lazy ? `const ${safeName(name)} = defineAsyncComponent(() => import(${JSON.stringify(source)}));` : `import ${safeName(name)} from ${JSON.stringify(source)};`; }
function mergedComponents(config: RevealTeXConfig): Record<string, ComponentDefinition> { return { ...Object.assign({}, ...((config.plugins ?? []).map(p => p.components ?? {}))), ...Object.fromEntries(Object.entries(config.components ?? {}).filter(([k]) => k !== "autoDiscover")) } as Record<string, ComponentDefinition>; }
function serializeJs(value: unknown): string { return JSON.stringify(value, null, 2); }
function stripUndefined<T extends object>(o: T): Partial<T> { return Object.fromEntries(Object.entries(o).filter(([,v]) => v !== undefined)) as Partial<T>; }
function columnWidth(value: string): string { const number = Number(value); return Number.isFinite(number) && number > 0 && number <= 1 ? `${number * 100}%` : value; }
function resolveSourceImport(path: string, sourceFile: string): string { return path.startsWith(".") && sourceFile !== "<input>" ? resolve(dirname(sourceFile), path) : path; }
function assetKey(src: string, file: string): string { return `${file}\0${src}`; }
function resolvableAssetPath(src: string, file: string): string | undefined { if (/^(?:[a-z]+:|\/|#)/i.test(src) || file.startsWith("<")) return undefined; return resolve(dirname(file), src); }
function assetAttribute(attribute: string, src: string, file: string, bindings: Map<string, string>): string { const binding = bindings.get(assetKey(src, file)); return binding ? `:${attribute}="${binding}"` : `${attribute}=${quote(src)}`; }
function mediaPresentationAttrs(options: Record<string, PropertyValue>, baseClass?: string): string { const classes = [baseClass, options.rounded === true && "rt-media--rounded", options.shadow === true && "rt-media--shadow"].filter(Boolean).join(" "); const width = typeof options.width === "string" || typeof options.width === "number" ? `width:${String(options.width)}` : ""; return `${classes ? ` class=${quote(classes)}` : ""}${width ? ` style=${quote(width)}` : ""}`; }
function quote(value: string): string { return JSON.stringify(value); }
function quoteBinding(value: unknown): string {
  // Vue directive values are JavaScript expressions. Single-quote the HTML
  // attribute so JSON's double-quoted strings remain valid expressions.
  return `'${JSON.stringify(value).replace(/&/g, "&amp;").replace(/'/g, "&#39;")}'`;
}
function safeName(value: string): string { return value.replace(/[^A-Za-z0-9_$]/g, "_").replace(/^[0-9]/, "_$&"); }
function escapeHtml(value: string): string { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }
function escapeComment(value: string): string { return value.replace(/-->/g, "--&gt;"); }
function indent(value: string, size: number): string { const pad = " ".repeat(size); return value.split("\n").map(l => pad + l).join("\n"); }
